"""
Django settings for Travel project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n27*8$*s10)41_v^!#25%rvm=@lpz@2o(9(s27bvq=a1p1g3+e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'travellapp',
    'Registration',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Travel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Travel.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
# STATIC_ROOT=os.path.join(BASE_DIR,'staticfile')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,"media")




"""
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Replace with your Redis server details
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
"""

# -----Multiple Social Media----

# Add the following at the end of the file
SOCIAL_AUTH_PROVIDERS = {
    'google': {
        'AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth',
        'TOKEN_URL': 'https://accounts.google.com/o/oauth2/token',
        'USER_INFO_URL': 'https://www.googleapis.com/oauth2/v2/userinfo',
        'CLIENT_ID': '947540323515-618mb135tr1v0c7fhaaej6hv6qhgs1gk.apps.googleusercontent.com',
        'CLIENT_SECRET': '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',
        'SCOPE': 'openid email profile',
    },
    'github': {
        'AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
        'TOKEN_URL': 'https://github.com/login/oauth/access_token',
        'USER_INFO_URL': 'https://api.github.com/user',
        'CLIENT_ID': 'YOUR_GITHUB_CLIENT_ID',
        'CLIENT_SECRET': 'YOUR_GITHUB_CLIENT_SECRET',
        'SCOPE': 'user',
    },
    # Add configurations for other providers like Facebook, Twitter, etc.
}

"""
GOOGLE_CLIENT_ID = '947540323515-618mb135tr1v0c7fhaaej6hv6qhgs1gk.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'

"""
