# Generated by Django 4.2.2 on 2023-07-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="auth_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
    ]
