# Generated by Django 4.2 on 2023-07-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0002_remove_profile_auth_token_remove_profile_is_verified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
