# Generated by Django 4.0.3 on 2023-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response_status',
            field=models.BooleanField(default=False),
        ),
    ]
