# Generated by Django 4.2.3 on 2023-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travellapp", "0002_contact_response_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("tra", "Travels"),
                            ("org", "Organizations"),
                            ("t&t", "Tips & Trics"),
                            ("unc", "Uncategories"),
                        ],
                        max_length=5,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "picture",
                    models.ImageField(max_length=50, upload_to="News/Pictures/"),
                ),
            ],
        ),
    ]
