# Generated by Django 4.2.3 on 2023-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travellapp", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.CharField(max_length=1000),
        ),
    ]
